### ISSUE TITLE
`Emoji` 정보의 url link 주소 오류

### ISSUE THREAD

**Issue by thisisWooyeol** [snuhcs-course/swpp-2023-project-team-2#55]
firestore에 저장된 emoji의 link를 android에서 불러와 재생하고자 하였을 때 파일을 불러오지 못함.
링크 자체가 잘못된 것으로 예상됨.(해당 PR: #54)

**Comment by yangchanhk98** [comment]
정상 작동하는 링크로 수정해서 PR올렸습니다!
